lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # 1 hora
    refresh_token_ttl: 604800 # 7 dias
    user_identity_field: email
    clock_skew: 0
    allow_no_expiration: false
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization 